# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InputSettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogInputSettings(object):
    def setupUi(self, DialogInputSettings):
        DialogInputSettings.setObjectName("DialogInputSettings")
        DialogInputSettings.resize(269, 227)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogInputSettings.sizePolicy().hasHeightForWidth())
        DialogInputSettings.setSizePolicy(sizePolicy)
        DialogInputSettings.setMinimumSize(QtCore.QSize(269, 227))
        DialogInputSettings.setMaximumSize(QtCore.QSize(269, 227))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(DialogInputSettings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(DialogInputSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.EndiannessFollowOutput = QtWidgets.QCheckBox(DialogInputSettings)
        self.EndiannessFollowOutput.setChecked(True)
        self.EndiannessFollowOutput.setObjectName("EndiannessFollowOutput")
        self.horizontalLayout.addWidget(self.EndiannessFollowOutput)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.EndianLittle = QtWidgets.QRadioButton(DialogInputSettings)
        self.EndianLittle.setEnabled(False)
        self.EndianLittle.setObjectName("EndianLittle")
        self.EndiannessGroup = QtWidgets.QButtonGroup(DialogInputSettings)
        self.EndiannessGroup.setObjectName("EndiannessGroup")
        self.EndiannessGroup.addButton(self.EndianLittle)
        self.horizontalLayout_2.addWidget(self.EndianLittle)
        self.EndianBig = QtWidgets.QRadioButton(DialogInputSettings)
        self.EndianBig.setEnabled(False)
        self.EndianBig.setObjectName("EndianBig")
        self.EndiannessGroup.addButton(self.EndianBig)
        self.horizontalLayout_2.addWidget(self.EndianBig)
        self.EndianNative = QtWidgets.QRadioButton(DialogInputSettings)
        self.EndianNative.setEnabled(False)
        self.EndianNative.setCheckable(True)
        self.EndianNative.setChecked(False)
        self.EndianNative.setObjectName("EndianNative")
        self.EndiannessGroup.addButton(self.EndianNative)
        self.horizontalLayout_2.addWidget(self.EndianNative)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(DialogInputSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.BinFormatFollowOutput = QtWidgets.QCheckBox(DialogInputSettings)
        self.BinFormatFollowOutput.setChecked(True)
        self.BinFormatFollowOutput.setObjectName("BinFormatFollowOutput")
        self.horizontalLayout_3.addWidget(self.BinFormatFollowOutput)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.FormatMS = QtWidgets.QRadioButton(DialogInputSettings)
        self.FormatMS.setEnabled(False)
        self.FormatMS.setObjectName("FormatMS")
        self.BinFormatGroup = QtWidgets.QButtonGroup(DialogInputSettings)
        self.BinFormatGroup.setObjectName("BinFormatGroup")
        self.BinFormatGroup.addButton(self.FormatMS)
        self.horizontalLayout_6.addWidget(self.FormatMS)
        self.FormatC1 = QtWidgets.QRadioButton(DialogInputSettings)
        self.FormatC1.setEnabled(False)
        self.FormatC1.setObjectName("FormatC1")
        self.BinFormatGroup.addButton(self.FormatC1)
        self.horizontalLayout_6.addWidget(self.FormatC1)
        self.FormatC2 = QtWidgets.QRadioButton(DialogInputSettings)
        self.FormatC2.setEnabled(False)
        self.FormatC2.setCheckable(True)
        self.FormatC2.setChecked(False)
        self.FormatC2.setObjectName("FormatC2")
        self.BinFormatGroup.addButton(self.FormatC2)
        self.horizontalLayout_6.addWidget(self.FormatC2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(DialogInputSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.SignFollowOutput = QtWidgets.QCheckBox(DialogInputSettings)
        self.SignFollowOutput.setChecked(True)
        self.SignFollowOutput.setObjectName("SignFollowOutput")
        self.horizontalLayout_5.addWidget(self.SignFollowOutput)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SignYes = QtWidgets.QRadioButton(DialogInputSettings)
        self.SignYes.setEnabled(False)
        self.SignYes.setObjectName("SignYes")
        self.horizontalLayout_4.addWidget(self.SignYes)
        self.SignNo = QtWidgets.QRadioButton(DialogInputSettings)
        self.SignNo.setEnabled(False)
        self.SignNo.setObjectName("SignNo")
        self.horizontalLayout_4.addWidget(self.SignNo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogInputSettings)
        self.buttonBox.setMaximumSize(QtCore.QSize(251, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(DialogInputSettings)
        QtCore.QMetaObject.connectSlotsByName(DialogInputSettings)

    def retranslateUi(self, DialogInputSettings):
        _translate = QtCore.QCoreApplication.translate
        DialogInputSettings.setWindowTitle(_translate("DialogInputSettings", "Input Settings"))
        self.label.setText(_translate("DialogInputSettings", "Endianness:"))
        self.EndiannessFollowOutput.setText(_translate("DialogInputSettings", "Follow output settings"))
        self.EndianLittle.setText(_translate("DialogInputSettings", "Little"))
        self.EndianBig.setText(_translate("DialogInputSettings", "Big"))
        self.EndianNative.setText(_translate("DialogInputSettings", "Native"))
        self.label_2.setText(_translate("DialogInputSettings", "Binary Format:"))
        self.BinFormatFollowOutput.setText(_translate("DialogInputSettings", "Follow output settings"))
        self.FormatMS.setText(_translate("DialogInputSettings", "MS"))
        self.FormatC1.setText(_translate("DialogInputSettings", "C1"))
        self.FormatC2.setText(_translate("DialogInputSettings", "C2"))
        self.label_3.setText(_translate("DialogInputSettings", "Signed: "))
        self.SignFollowOutput.setText(_translate("DialogInputSettings", "Follow output settings"))
        self.SignYes.setText(_translate("DialogInputSettings", "Yes"))
        self.SignNo.setText(_translate("DialogInputSettings", "No"))
