# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StringManager.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_StringManager(object):
    def setupUi(self, StringManager):
        StringManager.setObjectName("StringManager")
        StringManager.resize(394, 605)
        StringManager.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(StringManager)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(StringManager)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.CheckReadFromFile = QtWidgets.QCheckBox(StringManager)
        self.CheckReadFromFile.setObjectName("CheckReadFromFile")
        self.horizontalLayout.addWidget(self.CheckReadFromFile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.FrameIn = QtWidgets.QFrame(StringManager)
        self.FrameIn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameIn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameIn.setObjectName("FrameIn")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.FrameIn)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.FrameIn)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.AddrLineIn = QtWidgets.QLineEdit(self.FrameIn)
        self.AddrLineIn.setObjectName("AddrLineIn")
        self.horizontalLayout_5.addWidget(self.AddrLineIn)
        self.FileButtonIn = QtWidgets.QToolButton(self.FrameIn)
        self.FileButtonIn.setObjectName("FileButtonIn")
        self.horizontalLayout_5.addWidget(self.FileButtonIn)
        self.verticalLayout.addWidget(self.FrameIn)
        self.TextIn = QtWidgets.QTextEdit(StringManager)
        self.TextIn.setObjectName("TextIn")
        self.verticalLayout.addWidget(self.TextIn)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(StringManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.FormatBoxInput = QtWidgets.QComboBox(StringManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormatBoxInput.sizePolicy().hasHeightForWidth())
        self.FormatBoxInput.setSizePolicy(sizePolicy)
        self.FormatBoxInput.setObjectName("FormatBoxInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.FormatBoxInput)
        self.label_7 = QtWidgets.QLabel(StringManager)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.DecodeBox = QtWidgets.QComboBox(StringManager)
        self.DecodeBox.setObjectName("DecodeBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DecodeBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(StringManager)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(StringManager)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.CheckWriteToFile = QtWidgets.QCheckBox(StringManager)
        self.CheckWriteToFile.setObjectName("CheckWriteToFile")
        self.horizontalLayout_2.addWidget(self.CheckWriteToFile)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.FrameOut = QtWidgets.QFrame(StringManager)
        self.FrameOut.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameOut.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameOut.setObjectName("FrameOut")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FrameOut)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.FrameOut)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.AddrLineOut = QtWidgets.QLineEdit(self.FrameOut)
        self.AddrLineOut.setObjectName("AddrLineOut")
        self.horizontalLayout_4.addWidget(self.AddrLineOut)
        self.FileButtonOut = QtWidgets.QToolButton(self.FrameOut)
        self.FileButtonOut.setObjectName("FileButtonOut")
        self.horizontalLayout_4.addWidget(self.FileButtonOut)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.OptOverwrite = QtWidgets.QRadioButton(self.FrameOut)
        self.OptOverwrite.setObjectName("OptOverwrite")
        self.WriteOptions = QtWidgets.QButtonGroup(StringManager)
        self.WriteOptions.setObjectName("WriteOptions")
        self.WriteOptions.addButton(self.OptOverwrite)
        self.horizontalLayout_6.addWidget(self.OptOverwrite)
        self.OptAppend = QtWidgets.QRadioButton(self.FrameOut)
        self.OptAppend.setChecked(True)
        self.OptAppend.setObjectName("OptAppend")
        self.WriteOptions.addButton(self.OptAppend)
        self.horizontalLayout_6.addWidget(self.OptAppend)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.FrameOut)
        self.TextOut = QtWidgets.QTextEdit(StringManager)
        self.TextOut.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.TextOut.setObjectName("TextOut")
        self.verticalLayout.addWidget(self.TextOut)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(StringManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.FormatBoxOutput = QtWidgets.QComboBox(StringManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FormatBoxOutput.sizePolicy().hasHeightForWidth())
        self.FormatBoxOutput.setSizePolicy(sizePolicy)
        self.FormatBoxOutput.setObjectName("FormatBoxOutput")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.FormatBoxOutput)
        self.label_8 = QtWidgets.QLabel(StringManager)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.EncodeBox = QtWidgets.QComboBox(StringManager)
        self.EncodeBox.setObjectName("EncodeBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.EncodeBox)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.ConvertButton = QtWidgets.QPushButton(StringManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConvertButton.sizePolicy().hasHeightForWidth())
        self.ConvertButton.setSizePolicy(sizePolicy)
        self.ConvertButton.setMinimumSize(QtCore.QSize(60, 0))
        self.ConvertButton.setObjectName("ConvertButton")
        self.horizontalLayout_7.addWidget(self.ConvertButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(StringManager)
        QtCore.QMetaObject.connectSlotsByName(StringManager)

    def retranslateUi(self, StringManager):
        _translate = QtCore.QCoreApplication.translate
        StringManager.setWindowTitle(_translate("StringManager", "String manager"))
        self.label.setText(_translate("StringManager", "Input text"))
        self.CheckReadFromFile.setText(_translate("StringManager", "Read from file"))
        self.label_3.setText(_translate("StringManager", "Path:"))
        self.FileButtonIn.setText(_translate("StringManager", "..."))
        self.label_6.setText(_translate("StringManager", "Input format:"))
        self.label_7.setText(_translate("StringManager", "Decode from:"))
        self.label_2.setText(_translate("StringManager", "Output text"))
        self.CheckWriteToFile.setText(_translate("StringManager", "Write to file"))
        self.label_4.setText(_translate("StringManager", "Path:"))
        self.FileButtonOut.setText(_translate("StringManager", "..."))
        self.OptOverwrite.setText(_translate("StringManager", "Overwrite"))
        self.OptAppend.setText(_translate("StringManager", "Append"))
        self.label_5.setText(_translate("StringManager", "Output format:"))
        self.label_8.setText(_translate("StringManager", "Encode in:"))
        self.ConvertButton.setText(_translate("StringManager", "Convert"))
